### ISSUE TITLE
Include the code for the rest of the benchmark?

### ISSUE THREAD

**Issue by emmenlau** [romeric/expression_templates_benchmark#1]
Hi, thanks for the nice work!
I've just tried to reproduce the numbers with latest version of xtensor, but I'm under the impression that the git repo only contains the benchmaek for the views, not for the rest of the benchmark?

**Comment by emmenlau** [comment]
Hi, this would be quite helpful to have, i.e. so that xtensor could be improved...

**Comment by emmenlau** [comment]
Hey, is this still monitored?

**Comment by romeric** [comment]
Which part of the benchmark is unpublished?

**Comment by emmenlau** [comment]
I guess this can be closed now.
